import React from "react";
import { ComponentMeta, ComponentStory } from "@storybook/react";

import ProductTemplate from ".";

export default {
	title: "templates/ProductTemplate",
	component: ProductTemplate,
} as ComponentMeta<typeof ProductTemplate>;

const Template: ComponentStory<typeof ProductTemplate> = (args) => (
	<ProductTemplate {...args}>{args.children}</ProductTemplate>
);

export const Default = Template.bind({});
Default.args = {
	activatedSize: "S-M",
	productInfo: {
		product: {
			id: 1240,
			originalName: "Nike Futura Washed Bucket Hat Black",
			translatedName: "나이키 퓨추라 워시드 버킷햇 블랙",
			originalPrice: 0,
			gender: "streetwear_unisex",
			category: "accessories",
			color: "Black",
			styleCode: "DC3967-010",
			wishCnt: 1,
			brandName: "Nike",
			backgroundColor: "#f4f4f4",
			imageUrls: [
				"https://kream-phinf.pstatic.net/MjAyMTA1MjhfMTA4/MDAxNjIyMTgxNTI1Mjgy.YobSrrE7qQNmSttZm0uZJSHRM5RUn2LRtjjgb2u0Ch4g.xCk-UP-ZbCqtbQxNeeujnFgGYOI0nXw2hNgrdGLyekMg.JPEG/p_3196c4f319e4472b95e3c66e7544c2e6.jpg",
				"https://kream-phinf.pstatic.net/MjAyMTA1MjhfMTA1/MDAxNjIyMTgxNTI1Mjkx.T1kZ52Zn6WCa3eA1k7h3um43bixj8AkQIq3neuxbutEg.HsPTPgCZfmS0yuC9aT4o3GhD1ksxwRyssg0VebHHFQcg.JPEG/p_a7cc6254fcfa4fa4b14003216da0f0d8.jpg",
			],
			sizes: ["S-M", "M-L", "L-XL"],
			releasedDate: null,
			totalSale: 0,
			wishList: ["M-L"],
			lowestAsk: null,
			highestBid: null,
			premiumPrice: null,
		},
		lastCompletedTrades: [],
		asksBySizeCount: [],
		bidsBySizeCount: [],
		lastSalePrice: null,
		changePercentage: null,
		changeValue: null,
		pricePremiumPercentage: null,
		askPrices: {
			"S-M": 94000,
			"L-XL": null,
			"M-L": null,
		},
		bidPrices: {
			"S-M": null,
			"L-XL": null,
			"M-L": null,
		},
		relatedProducts: [
			{
				id: 1129,
				originalName: "Nike x Stussy Cuff Beanie White",
				translatedName: "나이키 x 스투시 커프 비니 화이트",
				originalPrice: 35000,
				gender: "streetwear_unisex",
				category: "accessories",
				color: "Summit White/Black",
				styleCode: "CV8961-121",
				wishCnt: 0,
				brandName: "Nike",
				backgroundColor: "#f4f4f4",
				imageUrls: [
					"https://kream-phinf.pstatic.net/MjAyMDEyMTBfMTAw/MDAxNjA3NjAwODc1OTQ3.YfXRbxcQcSRepQZ5iWS9gJHGYf4lyOOqbteSlX4-AgIg.koooruSkOBYnJlyoRxiw40M_diVITuZHH_l32fUvTRwg.JPEG/p_4631aed5af784555a0dcabe997763200.jpg",
				],
				sizes: ["ONE SIZE"],
				releasedDate: "2020-12-12",
				totalSale: 0,
				wishList: null,
				lowestAsk: null,
				highestBid: null,
				premiumPrice: null,
			},
			{
				id: 1133,
				originalName: "Nike ACG Warm AW84 Cap Black Anthracite",
				translatedName: "나이키 ACG 웜 AW84 블랙 앤트러사이트",
				originalPrice: 49000,
				gender: "streetwear_unisex",
				category: "accessories",
				color: "Black/Black/Anthracite",
				styleCode: "DM4703-010",
				wishCnt: 0,
				brandName: "Nike",
				backgroundColor: "#f4f4f4",
				imageUrls: [
					"https://kream-phinf.pstatic.net/MjAyMTExMDJfMTMw/MDAxNjM1ODE2NzQ5NjUw.ztHSxxS2Ywldq0Z6i2XRwZcT64s2-jpTZ8dL5IAeiUAg.ZAEB19gJU3P0T0ZL6o2_OQh_pFgoluufIARr73eF5Tkg.JPEG/a_1d66919e62674022b90672aa2506d9ca.jpg",
					"https://kream-phinf.pstatic.net/MjAyMTExMDJfMTAy/MDAxNjM1ODE2NzQ5NjU4.2yyKl2fAOdAEZfj-CEEkQvwY9qMm2ufsAfZPKTfGEV4g.z7Z8Xr1VWB6qHTcXnQcVDaowSeJ1QzTZnkg8KhhPUOcg.JPEG/a_fcc48b6a84f24932ba72d22adf3e867d.jpg",
				],
				sizes: ["ONE SIZE"],
				releasedDate: "2021-11-01",
				totalSale: 0,
				wishList: null,
				lowestAsk: null,
				highestBid: null,
				premiumPrice: null,
			},
			{
				id: 1135,
				originalName: "Nike NRG ACG Cuffed Beanie Black",
				translatedName: "나이키 NRG ACG 커프드 비니 블랙",
				originalPrice: 45000,
				gender: "streetwear_unisex",
				category: "accessories",
				color: "Black/Black",
				styleCode: "DM4706-010",
				wishCnt: 0,
				brandName: "Nike",
				backgroundColor: "#f4f4f4",
				imageUrls: [
					"https://kream-phinf.pstatic.net/MjAyMTExMDJfMjQg/MDAxNjM1ODQ3ODU0NTk2.XTMXCdsIIVY0LPDiDcamWcF5fVOaxE6i52pdrPJy6Tsg.dB0CGdvfmaNG196S_dqZSb_LhG5ryBwt1lSFS0dXe6cg.JPEG/a_947b0d63029b445595dfe838d4b207de.jpg",
					"https://kream-phinf.pstatic.net/MjAyMTExMDJfODAg/MDAxNjM1ODQ3ODU0NTk1.0Y-4ygnL9GVKpOByojmfcWmFIMQnf46kJrLfJINtv9kg.iVuzoezIrV2of40iQo7JQQ73UOMMiSZEGobG-8wo4DEg.JPEG/a_9ac58ad7b9d34541b9dd569477ccdf5c.jpg",
				],
				sizes: ["ONE SIZE"],
				releasedDate: null,
				totalSale: 0,
				wishList: null,
				lowestAsk: null,
				highestBid: null,
				premiumPrice: null,
			},
			{
				id: 1236,
				originalName: "Nike x Drake Nocta Gloves Black",
				translatedName: "나이키 x 드레이크 녹타 글러브 블랙",
				originalPrice: 100,
				gender: "streetwear_unisex",
				category: "accessories",
				color: "BLACK/BLACK/SILVER",
				styleCode: "DJ2880-082/N1003313082",
				wishCnt: 0,
				brandName: "Nike",
				backgroundColor: "#f4f4f4",
				imageUrls: [
					"https://kream-phinf.pstatic.net/MjAyMTAxMTFfNTUg/MDAxNjEwMzUxNTIzOTM2.UBU7Fsi9dSfjitRgAKnvuE0FGvJv9D-Q-WF9BbNChPog.wDo9IkjmLAoev_MD8J972a6BWbEfC23MI4RqxTZNUbog.JPEG/p_113df2c7db59470da6f9644aa408baa7.jpg",
					"https://kream-phinf.pstatic.net/MjAyMTAxMTFfMTE0/MDAxNjEwMzUxNTI2OTk4.hNkRyZU-qufK_0HD8ccMEZ-MhIJ4UjETdkgvgynZ4Asg.QrDbI3yky1YAEehU5T9roCJ6ZnFWC9pTHrqwW1zfe78g.JPEG/p_6185946d3a9c42f3be7bf78517eaf83f.jpg",
				],
				sizes: ["XS", "S", "M", "L", "XL", "XXL"],
				releasedDate: "2020-12-18",
				totalSale: 0,
				wishList: null,
				lowestAsk: null,
				highestBid: null,
				premiumPrice: null,
			},
			{
				id: 1239,
				originalName: "Nike NRG Bucket Hat Black",
				translatedName: "나이키 NRG 버킷햇 블랙",
				originalPrice: 39000,
				gender: "streetwear_unisex",
				category: "accessories",
				color: "Black",
				styleCode: "DM8518-010",
				wishCnt: 0,
				brandName: "Nike",
				backgroundColor: "#f4f4f4",
				imageUrls: [
					"https://kream-phinf.pstatic.net/MjAyMTA3MDFfMjUw/MDAxNjI1MTMxMTE2MTEx.B4rYppkFAw6fcG-_K775NV5I233FFL87WsCZoS30he8g.HnVceRNkxl184IYbC0tOEBvti36uYfOVnqdYXi0EGBYg.JPEG/p_2381f80597be4a6f909cc8c3221b12d6.jpg",
					"https://kream-phinf.pstatic.net/MjAyMTA3MDFfMjcy/MDAxNjI1MTMxMTE2MTEx.TidIZNujfR5HimT4MirDjnjxGPNvhMZXit0PBrBv914g.69n9XIFJjtRVQS3lJSMT_FlqEQ6vSJfmrkJWyyzUdLwg.JPEG/p_dac13ab2b94f4779b0ae701680f2ceec.jpg",
				],
				sizes: ["S-M", "M-L", "L-XL"],
				releasedDate: "2021-07-01",
				totalSale: 0,
				wishList: null,
				lowestAsk: null,
				highestBid: null,
				premiumPrice: null,
			},
			{
				id: 1129,
				originalName: "Nike x Stussy Cuff Beanie White",
				translatedName: "나이키 x 스투시 커프 비니 화이트",
				originalPrice: 35000,
				gender: "streetwear_unisex",
				category: "accessories",
				color: "Summit White/Black",
				styleCode: "CV8961-121",
				wishCnt: 0,
				brandName: "Nike",
				backgroundColor: "#f4f4f4",
				imageUrls: [
					"https://kream-phinf.pstatic.net/MjAyMDEyMTBfMTAw/MDAxNjA3NjAwODc1OTQ3.YfXRbxcQcSRepQZ5iWS9gJHGYf4lyOOqbteSlX4-AgIg.koooruSkOBYnJlyoRxiw40M_diVITuZHH_l32fUvTRwg.JPEG/p_4631aed5af784555a0dcabe997763200.jpg",
				],
				sizes: ["ONE SIZE"],
				releasedDate: "2020-12-12",
				totalSale: 0,
				wishList: null,
				lowestAsk: null,
				highestBid: null,
				premiumPrice: null,
			},
			{
				id: 1133,
				originalName: "Nike ACG Warm AW84 Cap Black Anthracite",
				translatedName: "나이키 ACG 웜 AW84 블랙 앤트러사이트",
				originalPrice: 49000,
				gender: "streetwear_unisex",
				category: "accessories",
				color: "Black/Black/Anthracite",
				styleCode: "DM4703-010",
				wishCnt: 0,
				brandName: "Nike",
				backgroundColor: "#f4f4f4",
				imageUrls: [
					"https://kream-phinf.pstatic.net/MjAyMTExMDJfMTMw/MDAxNjM1ODE2NzQ5NjUw.ztHSxxS2Ywldq0Z6i2XRwZcT64s2-jpTZ8dL5IAeiUAg.ZAEB19gJU3P0T0ZL6o2_OQh_pFgoluufIARr73eF5Tkg.JPEG/a_1d66919e62674022b90672aa2506d9ca.jpg",
					"https://kream-phinf.pstatic.net/MjAyMTExMDJfMTAy/MDAxNjM1ODE2NzQ5NjU4.2yyKl2fAOdAEZfj-CEEkQvwY9qMm2ufsAfZPKTfGEV4g.z7Z8Xr1VWB6qHTcXnQcVDaowSeJ1QzTZnkg8KhhPUOcg.JPEG/a_fcc48b6a84f24932ba72d22adf3e867d.jpg",
				],
				sizes: ["ONE SIZE"],
				releasedDate: "2021-11-01",
				totalSale: 0,
				wishList: null,
				lowestAsk: null,
				highestBid: null,
				premiumPrice: null,
			},
			{
				id: 1135,
				originalName: "Nike NRG ACG Cuffed Beanie Black",
				translatedName: "나이키 NRG ACG 커프드 비니 블랙",
				originalPrice: 45000,
				gender: "streetwear_unisex",
				category: "accessories",
				color: "Black/Black",
				styleCode: "DM4706-010",
				wishCnt: 0,
				brandName: "Nike",
				backgroundColor: "#f4f4f4",
				imageUrls: [
					"https://kream-phinf.pstatic.net/MjAyMTExMDJfMjQg/MDAxNjM1ODQ3ODU0NTk2.XTMXCdsIIVY0LPDiDcamWcF5fVOaxE6i52pdrPJy6Tsg.dB0CGdvfmaNG196S_dqZSb_LhG5ryBwt1lSFS0dXe6cg.JPEG/a_947b0d63029b445595dfe838d4b207de.jpg",
					"https://kream-phinf.pstatic.net/MjAyMTExMDJfODAg/MDAxNjM1ODQ3ODU0NTk1.0Y-4ygnL9GVKpOByojmfcWmFIMQnf46kJrLfJINtv9kg.iVuzoezIrV2of40iQo7JQQ73UOMMiSZEGobG-8wo4DEg.JPEG/a_9ac58ad7b9d34541b9dd569477ccdf5c.jpg",
				],
				sizes: ["ONE SIZE"],
				releasedDate: null,
				totalSale: 0,
				wishList: null,
				lowestAsk: null,
				highestBid: null,
				premiumPrice: null,
			},
			{
				id: 1236,
				originalName: "Nike x Drake Nocta Gloves Black",
				translatedName: "나이키 x 드레이크 녹타 글러브 블랙",
				originalPrice: 100,
				gender: "streetwear_unisex",
				category: "accessories",
				color: "BLACK/BLACK/SILVER",
				styleCode: "DJ2880-082/N1003313082",
				wishCnt: 0,
				brandName: "Nike",
				backgroundColor: "#f4f4f4",
				imageUrls: [
					"https://kream-phinf.pstatic.net/MjAyMTAxMTFfNTUg/MDAxNjEwMzUxNTIzOTM2.UBU7Fsi9dSfjitRgAKnvuE0FGvJv9D-Q-WF9BbNChPog.wDo9IkjmLAoev_MD8J972a6BWbEfC23MI4RqxTZNUbog.JPEG/p_113df2c7db59470da6f9644aa408baa7.jpg",
					"https://kream-phinf.pstatic.net/MjAyMTAxMTFfMTE0/MDAxNjEwMzUxNTI2OTk4.hNkRyZU-qufK_0HD8ccMEZ-MhIJ4UjETdkgvgynZ4Asg.QrDbI3yky1YAEehU5T9roCJ6ZnFWC9pTHrqwW1zfe78g.JPEG/p_6185946d3a9c42f3be7bf78517eaf83f.jpg",
				],
				sizes: ["XS", "S", "M", "L", "XL", "XXL"],
				releasedDate: "2020-12-18",
				totalSale: 0,
				wishList: null,
				lowestAsk: null,
				highestBid: null,
				premiumPrice: null,
			},
			{
				id: 1239,
				originalName: "Nike NRG Bucket Hat Black",
				translatedName: "나이키 NRG 버킷햇 블랙",
				originalPrice: 39000,
				gender: "streetwear_unisex",
				category: "accessories",
				color: "Black",
				styleCode: "DM8518-010",
				wishCnt: 0,
				brandName: "Nike",
				backgroundColor: "#f4f4f4",
				imageUrls: [
					"https://kream-phinf.pstatic.net/MjAyMTA3MDFfMjUw/MDAxNjI1MTMxMTE2MTEx.B4rYppkFAw6fcG-_K775NV5I233FFL87WsCZoS30he8g.HnVceRNkxl184IYbC0tOEBvti36uYfOVnqdYXi0EGBYg.JPEG/p_2381f80597be4a6f909cc8c3221b12d6.jpg",
					"https://kream-phinf.pstatic.net/MjAyMTA3MDFfMjcy/MDAxNjI1MTMxMTE2MTEx.TidIZNujfR5HimT4MirDjnjxGPNvhMZXit0PBrBv914g.69n9XIFJjtRVQS3lJSMT_FlqEQ6vSJfmrkJWyyzUdLwg.JPEG/p_dac13ab2b94f4779b0ae701680f2ceec.jpg",
				],
				sizes: ["S-M", "M-L", "L-XL"],
				releasedDate: "2021-07-01",
				totalSale: 0,
				wishList: null,
				lowestAsk: null,
				highestBid: null,
				premiumPrice: null,
			},
		],
	},
};

export const Example = Template.bind({});
Example.args = {
	activatedSize: "ONE SIZE",
	productInfo: {
		product: {
			id: 1241,
			originalName: "Stussy Metal Dice Keychain Silver",
			translatedName: "스투시 메탈 다이스 키체인 실버",
			originalPrice: 28000,
			gender: "streetwear_unisex",
			category: "accessories",
			color: "Silver",
			styleCode: "-",
			wishCnt: 0,
			brandName: "Stussy",
			backgroundColor: "#f4f4f4",
			imageUrls: [
				"https://kream-phinf.pstatic.net/MjAyMTA4MjZfMjI0/MDAxNjI5OTU0Mzg0Nzgy.LiSGRGMB6GsVfHcy_caMBJQKZ6AkVKdpCNRAAeRomIcg.I_xBxQToGT_I02XpJtQEIII93_Ht-7d3mN3N01kZ9U4g.JPEG/a_acf7333bb02548f3b7367f07207c3704.jpg",
			],
			sizes: ["ONE SIZE"],
			releasedDate: null,
			totalSale: 0,
			wishList: null,
			lowestAsk: null,
			highestBid: null,
			premiumPrice: null,
		},
		lastCompletedTrades: [],
		asksBySizeCount: [],
		bidsBySizeCount: [],
		lastSalePrice: null,
		changePercentage: null,
		changeValue: null,
		pricePremiumPercentage: null,
		askPrices: {
			"ONE SIZE": null,
		},
		bidPrices: {
			"ONE SIZE": null,
		},
		relatedProducts: [
			{
				id: 1139,
				originalName: "Stussy Basic Cuff Beanie Black 2021",
				translatedName: "스투시 베이직 커프 비니 블랙 2021",
				originalPrice: 54000,
				gender: "streetwear_unisex",
				category: "accessories",
				color: "Black",
				styleCode: "-",
				wishCnt: 0,
				brandName: "Stussy",
				backgroundColor: "#f4f4f4",
				imageUrls: [
					"https://kream-phinf.pstatic.net/MjAyMTA5MjhfNjcg/MDAxNjMyNzk1OTg2OTc0.qAAYI_1ZqQni5_rX7XB7N9DfgWKUii0wWlMXFJlNDpog.5-SxjOo8wgo2Lm7YqWTLfrgijvw7O8ICwiZnhCI8S8Mg.JPEG/a_312104b37b3a41dfb36f756b1aab3be0.jpg",
					"https://kream-phinf.pstatic.net/MjAyMTA5MjhfMjU0/MDAxNjMyNzk1OTg2OTgw.ikDzUTNIK2hFj5OeR3lN4PBRBWtkU7D6RXrEIlG7jJUg.5PnFzk4QO4mkuF0XNHWTeNJq4duQqYCK_JGVen9hPA4g.JPEG/a_5f01dce219c34863bbf3a81861185efb.jpg",
				],
				sizes: ["ONE SIZE"],
				releasedDate: null,
				totalSale: 0,
				wishList: null,
				lowestAsk: null,
				highestBid: null,
				premiumPrice: null,
			},
			{
				id: 1208,
				originalName: "Stussy Crochet Checker Beanie Black",
				translatedName: "스투시 크로쉐 체커 비니 블랙",
				originalPrice: 54000,
				gender: "streetwear_unisex",
				category: "accessories",
				color: "Black",
				styleCode: "-",
				wishCnt: 0,
				brandName: "Stussy",
				backgroundColor: "#f4f4f4",
				imageUrls: [
					"https://kream-phinf.pstatic.net/MjAyMTA4MjNfMTI2/MDAxNjI5NzA4NjMzNDA5.4n5uujifEafOPGCTpCbiYcqifa3zPcv_aBDHjyz8UAAg.GYRL1V2QgwXzWbp7-WM1xiI38tm2jFEewfyhOsR_BNEg.JPEG/a_0397a90eab3e49f886d4c13d59310ae5.jpg",
					"https://kream-phinf.pstatic.net/MjAyMTA4MjNfMjQg/MDAxNjI5NzA4NjM0OTA2.yHixH4jiArLK5VT_7K4miggGQDUs0mv-LZtWeKEd9nsg._1fMjuBE50LEEz1AFD-d8glI9Nr7mvfvLyhQnrlJOAUg.JPEG/a_21c779c30cac46d6ab232ee67fb8f599.jpg",
				],
				sizes: ["ONE SIZE"],
				releasedDate: "2021-08-20",
				totalSale: 0,
				wishList: null,
				lowestAsk: null,
				highestBid: null,
				premiumPrice: null,
			},
			{
				id: 1247,
				originalName: "Stussy Stock Cuff Beanie Black 2021",
				translatedName: "스투시 스탁 커프 비니 블랙 2021",
				originalPrice: 54000,
				gender: "streetwear_unisex",
				category: "accessories",
				color: "Black",
				styleCode: "-",
				wishCnt: 0,
				brandName: "Stussy",
				backgroundColor: "#f4f4f4",
				imageUrls: [
					"https://kream-phinf.pstatic.net/MjAyMTEwMDVfMTU0/MDAxNjMzNDI3ODUyMjUz.Fu_KiqdiLJfWYIaz5XJNFZMMn6za917FccLo_Zhj4U0g.iMWvqbnxrgQB5zfISQIyvRtHEB6jU4Gfa_2nafACuzwg.JPEG/a_8d9dbfa15ee54fa8a53c2c388de273c7.jpg",
					"https://kream-phinf.pstatic.net/MjAyMTEwMDVfMjg0/MDAxNjMzNDI3ODUyMjcz.0CxievbUIEzYqLbQut5247igK3PpeG-iFq6kKu8DXJUg.piU8Z03pc6ZqSOT_KV6V1KN0XMipsISicGV0_o5V5HQg.JPEG/a_ca2bf0ab5bec48f8a31898f0d9ecdcff.jpg",
				],
				sizes: ["ONE SIZE"],
				releasedDate: null,
				totalSale: 0,
				wishList: null,
				lowestAsk: null,
				highestBid: null,
				premiumPrice: null,
			},
			{
				id: 1255,
				originalName: "Stussy Debossed Basic Logo Beanie Black",
				translatedName: "스투시 디보스드 베이직 로고 비니 블랙",
				originalPrice: 54000,
				gender: "streetwear_unisex",
				category: "accessories",
				color: "BLACK",
				styleCode: "1321076",
				wishCnt: 0,
				brandName: "Stussy",
				backgroundColor: "#f4f4f4",
				imageUrls: [
					"https://kream-phinf.pstatic.net/MjAyMTExMDVfMTM1/MDAxNjM2MTEzNjc4MjIx.j29EUpW-j1WvHRs0GfqLn3NYZ0ae1jZE_PFJeDjWvfUg.LzwYngggyAf4IZTwmEzhAJtiHamkwsqhqCOUVOehCtAg.JPEG/a_5d43196ee8214cd6a3d0ef13b40d385f.jpg",
					"https://kream-phinf.pstatic.net/MjAyMTExMDVfOTQg/MDAxNjM2MTEzNjgwMzk5.q2gKRwUOBotAXXkghAMdd0vJPLaMFkXbtSsEDjlLh_Qg.Sow59AMYZ6iX3S-cbnOhHjYeA9yE9haW4TT51US0DFkg.JPEG/a_53ea43202631461ea87a5a7427117112.jpg",
				],
				sizes: ["ONE SIZE"],
				releasedDate: "2021-11-05",
				totalSale: 0,
				wishList: null,
				lowestAsk: null,
				highestBid: null,
				premiumPrice: null,
			},
			{
				id: 1258,
				originalName: "Stussy Debossed Basic Logo Beanie Blue",
				translatedName: "스투시 디보스드 베이직 로고 비니 블루",
				originalPrice: 54000,
				gender: "streetwear_unisex",
				category: "accessories",
				color: "BLUE",
				styleCode: "1321076",
				wishCnt: 0,
				brandName: "Stussy",
				backgroundColor: "#f4f4f4",
				imageUrls: [
					"https://kream-phinf.pstatic.net/MjAyMTExMDVfMTUg/MDAxNjM2MTEzODI1MzI5.RwViyUdt0GBygRwaK03kzn-n5lkyY7DY-A9VfxE0Gmkg.kXwWa8C7oZvPSLWmq59OfoYYmkM7hi86w9EjOUNF0WEg.JPEG/a_5f15b616c89c4dfea1bb7db4b1475382.jpg",
					"https://kream-phinf.pstatic.net/MjAyMTExMDVfMjM4/MDAxNjM2MTEzODI5MjM0.UXqpZxYPAn4N_-KtUVK0ZPbodOyMxsR_6RMhqmYFjucg.-OtVulEvNnUeYWm3SQHQUVUT87fg9NwPQTfXbjXBh7Yg.JPEG/a_468e072897b7466cb1cbfe12c3019c6e.jpg",
				],
				sizes: ["ONE SIZE"],
				releasedDate: "2021-11-05",
				totalSale: 0,
				wishList: null,
				lowestAsk: null,
				highestBid: null,
				premiumPrice: null,
			},
		],
	},
};
