server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://USER
          predicates:
            - Path=/users/**
          filters:
            - JwtAuthFilter
        - id: product
          uri: lb://PRODUCT
          predicates:
            - Path=/users/**
        - id: auction
          uri: lb://AUCTION
          predicates:
            - Path=/users/**

secret-key: 
auth-excluded-path: /users/login, /users/signup, /users/refresh, /users/verify, /users/validate