server:
  port: 8000
  address: 192.168.0.13

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    ip-address: ${server.address}
    instance-id: ${server.address}:${server.port}

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://USER
          predicates:
            - Path=/users/**
        - id: product
          uri: lb://PRODUCT
          predicates:
            - Path=/filters, /, /products/**, /trades/**, /wish/**
        - id: log
          uri: lb://LOG
          predicates:
            - Path=/prices/**, /recommendations/**, /log/**
      default-filters:
        - JwtAuthFilter

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allow-credentials: true
            allowedHeaders:
              - x-requested-with
              - authorization
              - content-type
              - credential
              - X-AUTH-TOKEN
              - X-CSRF-TOKEN
            allowedMethods:
              - POST
              - GET
              - PUT
              - OPTIONS
              - DELETE
              - PATCH

auth-included-path: /users/me, /users/validate, /users/logout, /users/update

secret-key: 