server:
  port: 8000

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://USER
          predicates:
            - Path=/users/**
          filters:
            - JwtAuthFilter
        - id: product
          uri: lb://PRODUCT
          predicates:
            - Path=/filters, /, /products/**, /trades/**, /wish/**
        - id: log
          uri: lb://LOG
          predicates:
            - Path=/prices/**, /recommendations/**, /log/**

auth-included-path: /users/me, /users/validate, /users/logout, /users/update

secret-key: 