# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cream' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cream
  pod 'Charts'
  pod 'ChartsRealm'

end
