server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username:
    password: 
    url: jdbc:mysql://localhost:3306/user_db

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: none
        format_sql: true
  mvc:
      pathmatch:
          matching-strategy: ant_path_matcher

  redis:
    host: 127.0.0.1
    port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
    client:
        fetch-registry: true
        register-with-eureka: true

secret-key: 
gateway-url: localhost:8000

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
