import React from "react";
import { ComponentStory, ComponentMeta } from "@storybook/react";

import HomeProduct from "./";

export default {
	title: "organisms/HomeProduct",
	component: HomeProduct,
} as ComponentMeta<typeof HomeProduct>;

const Template: ComponentStory<typeof HomeProduct> = (args) => (
	<HomeProduct {...args}>{args.children}</HomeProduct>
);

export const Default = Template.bind({});
Default.args = {
	imageUrl:
		"https://kream-phinf.pstatic.net/MjAyMjAxMjhfMjE4/MDAxNjQzMzYzODkyNTE2._6eteKF4YYSoOvklrXPV2aUC8lIgxukIVn1-ys5qNywg.jUAhXsyVVDESEBIYisTgiWD54D_7_WQYxMrW9Ikojq8g.PNG/a_bf4b1b7bfa24406c96cf9a8d0157a046.png?type=m_2560",
	bgColor: "#EEE",
	header: "Knit Collection",
	detail: "겨울-봄까지! 활용도 높은 니트",
	productInfo: [
		{
			backgroundColor: "#f4f4f4",
			brandName: "Polo Ralph Lauren",
			category: "streetwear",
			color: "gray",
			gender: "unisex",
			highestBid: 1,
			id: 1,
			imageUrls:
				"https://kream-phinf.pstatic.net/MjAyMjAxMDNfMjQ2/MDAxNjQxMTk0MTU4OTAz.iFlWZXvdVdxBfXDPR0WzCjLc016PYLPkRNoWNJX-Dcog.ZtfkW_G4T1wdsSPjLfA7HeoV5Fy2NOg0nq4BH5cldUAg.PNG/a_463faa3f82be472484727d084992bf62.png?type=m",
			lowestAsk: 1,
			originalName: "Polo Ralph Lauren Cable Knit Cotton Sweater Grey",
			originalPrice: 200000,
			premiumPrice: 200000,
			releasedDate: "20200110",
			sizes: "",
			styleCode: "",
			totalSale: 1,
			translatedName: "어쩌구",
			wishCnt: 12,
			wishList: ["1"],
		},
		{
			backgroundColor: "#f4f4f4",
			brandName: "Polo Ralph Lauren",
			category: "streetwear",
			color: "gray",
			gender: "unisex",
			highestBid: 1,
			id: 1,
			imageUrls:
				"https://kream-phinf.pstatic.net/MjAyMjAxMDNfMjQ2/MDAxNjQxMTk0MTU4OTAz.iFlWZXvdVdxBfXDPR0WzCjLc016PYLPkRNoWNJX-Dcog.ZtfkW_G4T1wdsSPjLfA7HeoV5Fy2NOg0nq4BH5cldUAg.PNG/a_463faa3f82be472484727d084992bf62.png?type=m",
			lowestAsk: 1,
			originalName: "Polo Ralph Lauren Cable Knit Cotton Sweater Grey",
			originalPrice: 200000,
			premiumPrice: 200000,
			releasedDate: "20200110",
			sizes: "",
			styleCode: "",
			totalSale: 1,
			translatedName: "어쩌구",
			wishCnt: 12,
			wishList: ["1"],
		},
		{
			backgroundColor: "#f4f4f4",
			brandName: "Polo Ralph Lauren",
			category: "streetwear",
			color: "gray",
			gender: "unisex",
			highestBid: 1,
			id: 1,
			imageUrls:
				"https://kream-phinf.pstatic.net/MjAyMjAxMDNfMjQ2/MDAxNjQxMTk0MTU4OTAz.iFlWZXvdVdxBfXDPR0WzCjLc016PYLPkRNoWNJX-Dcog.ZtfkW_G4T1wdsSPjLfA7HeoV5Fy2NOg0nq4BH5cldUAg.PNG/a_463faa3f82be472484727d084992bf62.png?type=m",
			lowestAsk: 1,
			originalName: "Polo Ralph Lauren Cable Knit Cotton Sweater Grey",
			originalPrice: 200000,
			premiumPrice: 200000,
			releasedDate: "20200110",
			sizes: "",
			styleCode: "",
			totalSale: 1,
			translatedName: "어쩌구",
			wishCnt: 12,
			wishList: ["1"],
		},
		{
			backgroundColor: "#f4f4f4",
			brandName: "Polo Ralph Lauren",
			category: "streetwear",
			color: "gray",
			gender: "unisex",
			highestBid: 1,
			id: 1,
			imageUrls:
				"https://kream-phinf.pstatic.net/MjAyMjAxMDNfMjQ2/MDAxNjQxMTk0MTU4OTAz.iFlWZXvdVdxBfXDPR0WzCjLc016PYLPkRNoWNJX-Dcog.ZtfkW_G4T1wdsSPjLfA7HeoV5Fy2NOg0nq4BH5cldUAg.PNG/a_463faa3f82be472484727d084992bf62.png?type=m",
			lowestAsk: 1,
			originalName: "Polo Ralph Lauren Cable Knit Cotton Sweater Grey",
			originalPrice: 200000,
			premiumPrice: 200000,
			releasedDate: "20200110",
			sizes: "",
			styleCode: "",
			totalSale: 1,
			translatedName: "어쩌구",
			wishCnt: 12,
			wishList: ["1"],
		},
		{
			backgroundColor: "#f4f4f4",
			brandName: "Polo Ralph Lauren",
			category: "streetwear",
			color: "gray",
			gender: "unisex",
			highestBid: 1,
			id: 1,
			imageUrls:
				"https://kream-phinf.pstatic.net/MjAyMjAxMDNfMjQ2/MDAxNjQxMTk0MTU4OTAz.iFlWZXvdVdxBfXDPR0WzCjLc016PYLPkRNoWNJX-Dcog.ZtfkW_G4T1wdsSPjLfA7HeoV5Fy2NOg0nq4BH5cldUAg.PNG/a_463faa3f82be472484727d084992bf62.png?type=m",
			lowestAsk: 1,
			originalName: "Polo Ralph Lauren Cable Knit Cotton Sweater Grey",
			originalPrice: 200000,
			premiumPrice: 200000,
			releasedDate: "20200110",
			sizes: "",
			styleCode: "",
			totalSale: 1,
			translatedName: "어쩌구",
			wishCnt: 12,
			wishList: ["1"],
		},
		{
			backgroundColor: "#f4f4f4",
			brandName: "Polo Ralph Lauren",
			category: "streetwear",
			color: "gray",
			gender: "unisex",
			highestBid: 1,
			id: 1,
			imageUrls:
				"https://kream-phinf.pstatic.net/MjAyMjAxMDNfMjQ2/MDAxNjQxMTk0MTU4OTAz.iFlWZXvdVdxBfXDPR0WzCjLc016PYLPkRNoWNJX-Dcog.ZtfkW_G4T1wdsSPjLfA7HeoV5Fy2NOg0nq4BH5cldUAg.PNG/a_463faa3f82be472484727d084992bf62.png?type=m",
			lowestAsk: 1,
			originalName: "Polo Ralph Lauren Cable Knit Cotton Sweater Grey",
			originalPrice: 200000,
			premiumPrice: 200000,
			releasedDate: "20200110",
			sizes: "",
			styleCode: "",
			totalSale: 1,
			translatedName: "어쩌구",
			wishCnt: 12,
			wishList: ["1"],
		},
		{
			backgroundColor: "#f4f4f4",
			brandName: "Polo Ralph Lauren",
			category: "streetwear",
			color: "gray",
			gender: "unisex",
			highestBid: 1,
			id: 1,
			imageUrls:
				"https://kream-phinf.pstatic.net/MjAyMjAxMDNfMjQ2/MDAxNjQxMTk0MTU4OTAz.iFlWZXvdVdxBfXDPR0WzCjLc016PYLPkRNoWNJX-Dcog.ZtfkW_G4T1wdsSPjLfA7HeoV5Fy2NOg0nq4BH5cldUAg.PNG/a_463faa3f82be472484727d084992bf62.png?type=m",
			lowestAsk: 1,
			originalName: "Polo Ralph Lauren Cable Knit Cotton Sweater Grey",
			originalPrice: 200000,
			premiumPrice: 200000,
			releasedDate: "20200110",
			sizes: "",
			styleCode: "",
			totalSale: 1,
			translatedName: "어쩌구",
			wishCnt: 12,
			wishList: ["1"],
		},
		{
			backgroundColor: "#f4f4f4",
			brandName: "Polo Ralph Lauren",
			category: "streetwear",
			color: "gray",
			gender: "unisex",
			highestBid: 1,
			id: 1,
			imageUrls:
				"https://kream-phinf.pstatic.net/MjAyMjAxMDNfMjQ2/MDAxNjQxMTk0MTU4OTAz.iFlWZXvdVdxBfXDPR0WzCjLc016PYLPkRNoWNJX-Dcog.ZtfkW_G4T1wdsSPjLfA7HeoV5Fy2NOg0nq4BH5cldUAg.PNG/a_463faa3f82be472484727d084992bf62.png?type=m",
			lowestAsk: 1,
			originalName: "Polo Ralph Lauren Cable Knit Cotton Sweater Grey",
			originalPrice: 200000,
			premiumPrice: 200000,
			releasedDate: "20200110",
			sizes: "",
			styleCode: "",
			totalSale: 1,
			translatedName: "어쩌구",
			wishCnt: 12,
			wishList: ["1"],
		},
		{
			backgroundColor: "#f4f4f4",
			brandName: "Polo Ralph Lauren",
			category: "streetwear",
			color: "gray",
			gender: "unisex",
			highestBid: 1,
			id: 1,
			imageUrls:
				"https://kream-phinf.pstatic.net/MjAyMjAxMDNfMjQ2/MDAxNjQxMTk0MTU4OTAz.iFlWZXvdVdxBfXDPR0WzCjLc016PYLPkRNoWNJX-Dcog.ZtfkW_G4T1wdsSPjLfA7HeoV5Fy2NOg0nq4BH5cldUAg.PNG/a_463faa3f82be472484727d084992bf62.png?type=m",
			lowestAsk: 1,
			originalName: "Polo Ralph Lauren Cable Knit Cotton Sweater Grey",
			originalPrice: 200000,
			premiumPrice: 200000,
			releasedDate: "20200110",
			sizes: "",
			styleCode: "",
			totalSale: 1,
			translatedName: "어쩌구",
			wishCnt: 12,
			wishList: ["1"],
		},
		{
			backgroundColor: "#f4f4f4",
			brandName: "Polo Ralph Lauren",
			category: "streetwear",
			color: "gray",
			gender: "unisex",
			highestBid: 1,
			id: 1,
			imageUrls:
				"https://kream-phinf.pstatic.net/MjAyMjAxMDNfMjQ2/MDAxNjQxMTk0MTU4OTAz.iFlWZXvdVdxBfXDPR0WzCjLc016PYLPkRNoWNJX-Dcog.ZtfkW_G4T1wdsSPjLfA7HeoV5Fy2NOg0nq4BH5cldUAg.PNG/a_463faa3f82be472484727d084992bf62.png?type=m",
			lowestAsk: 1,
			originalName: "Polo Ralph Lauren Cable Knit Cotton Sweater Grey",
			originalPrice: 200000,
			premiumPrice: 200000,
			releasedDate: "20200110",
			sizes: "",
			styleCode: "",
			totalSale: 1,
			translatedName: "어쩌구",
			wishCnt: 12,
			wishList: ["1"],
		},
		{
			backgroundColor: "#f4f4f4",
			brandName: "Polo Ralph Lauren",
			category: "streetwear",
			color: "gray",
			gender: "unisex",
			highestBid: 1,
			id: 1,
			imageUrls:
				"https://kream-phinf.pstatic.net/MjAyMjAxMDNfMjQ2/MDAxNjQxMTk0MTU4OTAz.iFlWZXvdVdxBfXDPR0WzCjLc016PYLPkRNoWNJX-Dcog.ZtfkW_G4T1wdsSPjLfA7HeoV5Fy2NOg0nq4BH5cldUAg.PNG/a_463faa3f82be472484727d084992bf62.png?type=m",
			lowestAsk: 1,
			originalName: "Polo Ralph Lauren Cable Knit Cotton Sweater Grey",
			originalPrice: 200000,
			premiumPrice: 200000,
			releasedDate: "20200110",
			sizes: "",
			styleCode: "",
			totalSale: 1,
			translatedName: "어쩌구",
			wishCnt: 12,
			wishList: ["1"],
		},
	],
};
